name: project_submission

on:
  workflow_dispatch:
  pull_request:
    paths:
      - projects/tt_um_*/**

jobs:
  check_submission:
    name: Check user project submission
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r tt-multiplexer/py/requirements.txt -r tt/requirements.txt

      - name: Update caravel configuration
        run: python ./tt/configure.py --update-shuttle

      - name: upload shuttle_index.json
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: shuttle_index
          path: shuttle_index.json
